name: meme
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.68
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.68
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.10.14
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.34.2
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.34.2
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - av==13.1.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.44.1
      - bleach==6.1.0
      - cachetools==5.5.0
      - cffi==1.17.1
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.0.1
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.31.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.2
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gguf==0.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.23.0
      - google-api-python-client==2.153.0
      - google-auth==2.36.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.67.1
      - grpcio-status==1.67.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.2
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - idna==3.10
      - imagehash==4.3.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.27.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jieba==0.42.1
      - jiter==0.5.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - kagglehub==0.3.3
      - kiwisolver==1.4.7
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - metagen==0.7.4
      - mistral-common==1.4.4
      - mistral-inference==1.4.0
      - mistune==3.0.2
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - openai==1.48.0
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - orjson==3.10.12
      - outlines==0.0.46
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post4
      - peft==0.12.0
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.47
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.19
      - python-slugify==8.0.4
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyzmq==26.2.0
      - qwen-vl-utils==0.0.8
      - ray==2.37.0
      - referencing==0.35.1
      - regex==2024.9.11
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rouge-chinese==1.0.3
      - rpds-py==0.20.0
      - rsa==4.9
      - ruff==0.8.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.15.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - simple-parsing==0.1.6
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sse-starlette==2.1.3
      - stack-data==0.6.3
      - starlette==0.40.0
      - sympy==1.13.3
      - termcolor==2.4.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tinycss2==1.3.0
      - tokenizers==0.20.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torch==2.4.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.45.1
      - transformers-stream-generator==0.0.5
      - trl==0.9.6
      - typer==0.14.0
      - types-python-dateutil==2.9.0.20240906
      - typing-extensions==4.12.2
      - tyro==0.8.14
      - tzdata==2024.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vllm==0.6.3
      - wandb==0.18.3
      - watchfiles==0.24.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - widgetsnbextension==4.0.13
      - xformers==0.0.27.post2
      - xgboost==2.1.3
      - xxhash==3.5.0
      - yarl==1.15.3
      - zipp==3.20.2
